sudo: false

language: node_js

node_js:
  - '12'

branches:
  only:
    - master
    - travis-ci

before_install:
  - for dir in edify.*; do (cd $dir && npm install --no-save --no-package-lock); done
  - npm install -g nyc mocha
  - git checkout .

script:
  - nyc npm test
