sudo: false

language: node_js

node_js:
  - 4
  - 6

branches:
  only:
    - master
    - travis-ci

before_install:
  - npm install proof istanbul
  - for dir in edify.*; do (cd $dir && npm install); done

script: t/test
