sudo: false

language: node_js

node_js:
  - 4

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install && npm install istanbul
  - for dir in edify.*; do (cd $dir && npm install); done

script: echo 0
